app/models.py
from flask_login import UserMixin
from app import db, login_manager
import urllib2
import json
from config import *


class PredecirAsistencia(object):

    def __init__(self):
        self.prediccion_asistencia = 0
        self.score = 0

    def get(self, form):

        data = {"DiasSemana": form.diasSemana.data,
                     "NroMes": form.nroMes.data,
                     "delta_idas": form.deltaDias.data,
                     "edad": form.edad.data,
                     "prom_asistencia": form.promAsistencia.data,
                     "Sexo": str(form.sexo.data)}

        req = urllib2.Request(URL_POST_PREDICT)
        req.add_header('Content-Type', 'application/json')
        response = urllib2.urlopen(req, json.dumps(data))

        if response.code == 200:
            prediccion = json.load(response)
            self.prediccion_asistencia = prediccion['prediccion_asistencia']
            self.score = prediccion['score']
            return True
        else:
            return False


class Employee(UserMixin, db.Model):
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(60), index=True, unique=True)
    keyapi = ''
    password_hash = db.Column(db.String(128))
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        self.password_hash = password

    def verify_password(self, password):
        return self.password_hash == password

    def __repr__(self):
        return '<Employee: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return Employee.query.get(int(user_id))

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError, validators, FieldList, SelectField, \
    IntegerField, FloatField
from wtforms.validators import DataRequired, Email, EqualTo


class FormPredecir(FlaskForm):
    diasSemana = SelectField('Dia de Semana',
                             choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'),
                                      (6, 'Sabado')], coerce=int)
    nroMes = SelectField('Mes',
                             choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'),
                                      (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'),
                                      (11, 'Noviembre'), (12, 'Diciembre')], coerce=int)

    deltaDias = IntegerField('Cantidad dias espera al turno', validators=[DataRequired()])
    edad = IntegerField('Edad del paciente', validators=[DataRequired()])
    promAsistencia = FloatField('Promedio Asistencia', validators=[DataRequired()])
    sexo = SelectField(u'Sexo', choices=[('F', 'Femenino'), ('M', 'Masculino')])

    submit = SubmitField('Predecir')

app/__init__.py
# third-party imports
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import *

# local imports
from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')

    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_message = "Debe logonearse para acceder a esta pagina."
    login_manager.login_view = "auth.login"
    # migrate = Migrate(app, db)

    from app import models

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import flash, render_template, abort
from flask_login import login_required, current_user
from forms import FormPredecir
from ..models import PredecirAsistencia
from . import home


def check_admin():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)


@home.route('/')
def homepage():
    return render_template('home/index.html', title="Desafio Final")


@home.route('/predecir', methods=['GET', 'POST'])
@login_required
def patient():
    form = FormPredecir()
    if form.validate_on_submit():
        # register = RegisterPortal()
        # if register.get(form.nrohc.data):
        register = PredecirAsistencia()
        if register.get(form):
            if register.prediccion_asistencia == 1:
                result = 'Asistira'
            else:
                result = 'NO Asistira'
            flash('El paciente:' + result , 'warning')
            flash('Metrica prediccion:' + str(register.score), 'warning')
            #return redirect(url_for('home.resultado', nrohc=register.nrohc))
        else:
            flash('Sevicio de prediccion no disponible.')
    return render_template('home/predecir.html', form=form, title="Desarfio Final")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Desafío Final Data Science 2018</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('home.patient') }}">Predecir</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    <li><a><i class="fa fa-user"></i>  Hola, {{ current_user.username }}!</a></li>
                  {% else %}
                    <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
{#                    <li><a href="{{ url_for('auth.register') }}">RegistroApp</a></li>#}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                  {% endif %}
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">&sdot;</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
{#                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>#}
{#                          <li class="footer-menu-divider">&sdot;</li>#}
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">Curso Data Science Digital House &copy; 2018</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/home/dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Paciente{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Predecir asistencia</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1 style="color:black;">PREDICCION ASISTENCIA TURNOS MEDICOS</h1>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/predecir.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Paciente{% endblock %}
{% block body %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Predecir asistencia de turno Medico</h1>
    <br/>
    {{ wtf.quick_form(form) }}
    <br/>

  </div>
</div>
{% endblock %}

app/templates/home/resultado.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Paciente{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
{#    <div class="middle">#}
      <div style="width:100%; margin:0 auto;">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Detalle de la Registracion</h1>

          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="6%"> Nro HC </th>
                  <th width="25%"> Apellido y Nombre </th>
                {% if data.tutoractivo == True %}
                    <th width="15%"> Email Responsable </th>
                {% else %}
                    <th width="15%"> Email </th>
                {% endif %}
                  <th width="11%"> Fecha Nacimiento </th>
                    <th width="2%"> Confirmado Email</th>
                  <th width="11%"> Tipo Nro Doc </th>
                    <th width="5%"> Bloqueado </th>
                    {% if data.confirmado == 'NO' %}
                        <th width="5%"> Reenvio Confirmacion </th>
                        <th width="9%"> Eliminar Registro </th>
                    {% endif %}
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td> {{ data.nrohc }} </td>
                  <td> {{ data.apynom }} </td>
                {% if data.tutoractivo == True %}
                    <td> {{ data.tutoremail }} </td>
                {% else %}
                    <td> {{ data.email }} </td>
                {% endif %}

                    <td> {{ data.fechanacim }} </td>
                    <td align="center"> {{ data.confirmado }} </td>
                    <td> {{ data.tiponrodoc }} </td>
                    <td align="center"> {{ data.bloqueado }} </td>
                    {% if data.confirmado == "NO" %}
                      <td>
                        <a href="{{ url_for('home.send_register', nrohc=data.nrohc) }}">
                          <i class="fa fa-envelope"></i> Envio email
                        </a>
                      </td>
                      <td>
                        <a href="{{ url_for('home.delete_register', nrohc=data.nrohc) }}">
                          <i class="fa fa-trash"></i> Borrar
                        </a>
                      </td>
                    {% endif %}
                </tr>

              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}